# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-24 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='used_wildcard',
        ),
        migrations.AddField(
            model_name='membership',
            name='isFailed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='used_wildcard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
